<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TrainingType;
use App\Models\EmployeeTraining;
use App\Models\Employee;

class TrainingSeeder extends Seeder
{
    public function run(): void
    {
        // ── 1. Master Jenis Training ──────────────────────────────────
        $types = [
            // [nama, masa_berlaku_tahun (null=seumur hidup), has_nilai, has_expired, urutan]
            ['HES Induction',              null, false, false, 1],
            ['SWP PT HA',                  2,    true,  true,  2],
            ['MVSHE & LV',                 null, false, false, 3],
            ['Spotter & Flagman',          null, false, false, 4],
            ['SWP Excavation',             2,    false, true,  5],
            ['Training Lifting & Rigging', null, false, false, 6],
            ['FA DA FB',                   3,    false, true,  7],
            ['SWP Otorisasi PMCOW',        1,    false, true,  8],
            ['SWP QGT',                    2,    false, true,  9],
            ['DTAL & Spotter',             null, false, false, 10],
            ['K3U',                        5,    false, true,  11],
            ['SWP PGD',                    2,    false, true,  12],
            ['SWP Hot Work',               2,    false, true,  13],
        ];

        $typeMap = [];
        foreach ($types as [$nama, $masa, $has_nilai, $has_expired, $urutan]) {
            $t = TrainingType::updateOrCreate(
                ['nama' => $nama],
                [
                    'masa_berlaku_tahun' => $masa,
                    'has_nilai'          => $has_nilai,
                    'has_expired'        => $has_expired || ($masa !== null),
                    'is_active'          => true,
                    'urutan'             => $urutan,
                ]
            );
            $typeMap[$nama] = $t->id;
        }
        $this->command->info('✅ Training types: ' . count($typeMap) . ' jenis');

        // ── 2. Data Training per Karyawan ─────────────────────────────
        // [nama_karyawan, jenis_training, tanggal, trainer, nilai, status, expired]
        $data = [
            // Format: ['NAMA', 'JENIS TRAINING', 'tgl/null', 'trainer/null', 'nilai/null', 'status/null', 'expired/null']
            ['BAWONO WIJAYANTO WIRANJAYA', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['BAWONO WIJAYANTO WIRANJAYA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['BAWONO WIJAYANTO WIRANJAYA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['SUNARTO', 'HES Induction', '2023-02-23', 'FRANS PAOLO M', null, null, null],
            ['SUNARTO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['YASNI PINAL', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['YASNI PINAL', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '87', 'PASS', null],
            ['YASNI PINAL', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['SATRIA AFRIZA', 'HES Induction', '2024-04-23', 'FRANS PAOLO M', null, null, null],
            ['SATRIA AFRIZA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['JOSUA WIRONI HUTASOIT', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['JOSUA WIRONI HUTASOIT', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['JOSUA WIRONI HUTASOIT', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['FAJAR FEBRIAN', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['FAJAR FEBRIAN', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['FAJAR FEBRIAN', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['M PRIYO SUDARMONO', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['M PRIYO SUDARMONO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '87', 'PASS', null],
            ['M PRIYO SUDARMONO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['IRFAN DASMANTO', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['IRFAN DASMANTO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['IRFAN DASMANTO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['M ALIEF DARMAWANSYAH', 'HES Induction', '2024-01-17', 'Rini Oktora', null, null, null],
            ['M ALIEF DARMAWANSYAH', 'SWP PT HA', '2024-01-16', 'Baskara Herumukti', '93', 'PASS', null],
            ['M ALIEF DARMAWANSYAH', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['FACHRI AZMI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['MUHAMMAD RAPIQI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['MUHAMMAD RAPIQI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['MUHAMMAD RAPIQI', 'Spotter & Flagman', '2021-11-15', null, null, null, null],
            ['MUHAMMAD RAPIQI', 'FA DA FB', '2024-10-15', 'Baskara Herumukti', null, null, null],
            ['MUHAMMAD RAPIQI', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['MUHAMMAD RAPIQI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['HAVIZ AL RASYID', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['HAVIZ AL RASYID', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '87', 'PASS', null],
            ['HAVIZ AL RASYID', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['OKI CHARLES', 'HES Induction', '2023-08-24', 'Frans Paolo M', null, null, null],
            ['OKI CHARLES', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['OKI CHARLES', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['JHON HENDRI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['JHON HENDRI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '87', 'PASS', null],
            ['JHON HENDRI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['SUPRIADI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['SUPRIADI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['SUPRIADI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['AHMAD SYAH', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['AHMAD SYAH', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['AHMAD SYAH', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['AHMAD SYAH', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['AZLAN EFENDI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['AZLAN EFENDI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['AZLAN EFENDI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['AZLAN EFENDI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['BUDI HANDOKO', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['BUDI HANDOKO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['BUDI HANDOKO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['BUDI HANDOKO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['DEDEK SUSANTO', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['DEDEK SUSANTO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['DEDEK SUSANTO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['DEDEK SUSANTO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['IDRIS', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['IDRIS', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['IDRIS', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['IDRIS', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['LACTOGEN NAINGGOLAN', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['LACTOGEN NAINGGOLAN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['LACTOGEN NAINGGOLAN', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['M NUR', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['M NUR', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['M NUR', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['M NUR', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['RATNO WIYONO', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['RATNO WIYONO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['RATNO WIYONO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['RATNO WIYONO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['SATRIYON', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['SATRIYON', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '60', 'NO PASS', null],
            ['SATRIYON', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['SATRIYON', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['ALMEDI INDRA', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['ALMEDI INDRA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ALMEDI INDRA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ALMEDI INDRA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['ANDRE ISMAWIR', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['ANDRE ISMAWIR', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '73', 'PASS', null],
            ['ANDRE ISMAWIR', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ANDRE ISMAWIR', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['BAHTERA NEDI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['BAHTERA NEDI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['BAHTERA NEDI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['BAHTERA NEDI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['ANDRI', 'HES Induction', '2023-06-16', 'SYARIFUDDIN', null, null, null],
            ['ANDRI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ANDRI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ANDRI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['BUJANG PAMAN', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['BUJANG PAMAN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '70', 'PASS', null],
            ['BUJANG PAMAN', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['BUJANG PAMAN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['DENI ADE PUTRA', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['DENI ADE PUTRA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '94', 'PASS', null],
            ['DENI ADE PUTRA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['DENI ADE PUTRA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['JUFRIZAL', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['JUFRIZAL', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '80', 'PASS', null],
            ['JUFRIZAL', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['JUFRIZAL', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['KISWADI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['KISWADI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '81', 'PASS', null],
            ['KISWADI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['KISWADI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['NAHARUDIN', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['NAHARUDIN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['NAHARUDIN', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['NAHARUDIN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['NURDIANTO', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['NURDIANTO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['NURDIANTO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['NURDIANTO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['SYAFRI ADI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['SYAFRI ADI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['SYAFRI ADI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['SYAFRI ADI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['TARULI NAIBAHO', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['TARULI NAIBAHO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['TARULI NAIBAHO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['TARULI NAIBAHO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['TUKINO', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['TUKINO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['TUKINO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['TUKINO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['YULHENDRI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['YULHENDRI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['YULHENDRI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['YULHENDRI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['YUNASRIL', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['YUNASRIL', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['YUNASRIL', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['YUNASRIL', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['DEZITA CHANDRA', 'HES Induction', '2023-03-08', 'SYARIFUDDIN', null, null, null],
            ['DEZITA CHANDRA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['DEZITA CHANDRA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['HENDRA FERI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['HENDRA FERI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['HENDRA FERI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ROBBI SAPUTRA', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['ROBBI SAPUTRA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ROBBI SAPUTRA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['WELDI RUSDI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['WELDI RUSDI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['WELDI RUSDI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['DAMAR WULAN', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['DAMAR WULAN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['DAMAR WULAN', 'Spotter & Flagman', '2021-11-15', null, null, null, null],
            ['DAMAR WULAN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['ABDUL RAHMAN', 'HES Induction', '2023-05-08', 'Frans Paolo M', null, null, null],
            ['ABDUL RAHMAN', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ABDUL RAHMAN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['UMAR ARIS MUNADAR', 'HES Induction', '2024-07-19', 'Baskara Herumukti', null, null, null],
            ['UMAR ARIS MUNADAR', 'SWP PT HA', '2024-07-19', 'Baskara Herumukti', '93', 'PASS', null],
            ['BAMBANG TRISNO', 'HES Induction', '2023-05-08', 'Frans Paolo M', null, null, null],
            ['BAMBANG TRISNO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '70', 'PASS', null],
            ['BAMBANG TRISNO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['SALMAN SYOBRI', 'HES Induction', '2024-02-02', 'Syarifuddin', null, null, null],
            ['SALMAN SYOBRI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '73', 'PASS', null],
            ['WAWAN RIANDRA', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['WAWAN RIANDRA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['WAWAN RIANDRA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['R GARRY PATRIA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['R GARRY PATRIA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['ERI SUDHARMAN', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['ERI SUDHARMAN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['WIHANDRI SENJAYA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['WIHANDRI SENJAYA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ALENDRA NAULY.S', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['ALENDRA NAULY.S', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ALENDRA NAULY.S', 'SWP QGT', '2024-10-23', 'BASKARA HERUMUKTI', null, null, null],
            ['ALENDRA NAULY.S', 'K3U', null, null, 'LSP/BNSP', null, '2026-07-16'],
            ['RAFICO ADE MARTA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['RAFICO ADE MARTA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '87', 'PASS', null],
            ['RAFICO ADE MARTA', 'SWP QGT', '2024-10-23', 'BASKARA HERUMUKTI', null, null, null],
            ['RAFICO ADE MARTA', 'K3U', null, null, 'LSP/BNSP', null, '2027-11-07'],
            ['MUHAMMAD AGUNG PERDANA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['MUHAMMAD AGUNG PERDANA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', null, null],
            ['MUHAMMAD AGUNG PERDANA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['MUHAMMAD AGUNG PERDANA', 'SWP QGT', '2024-10-23', 'BASKARA HERUMUKTI', null, null, null],
            ['MUHAMMAD AGUNG PERDANA', 'K3U', null, null, 'KEMENAKER', null, '2027-08-20'],
            ['RAMZA ISWADI', 'HES Induction', '2024-04-24', 'Frans Paolo M', null, null, null],
            ['RAMZA ISWADI', 'SWP PT HA', '2024-03-23', 'Baskara Herumukti', '93', 'PASS', null],
            ['RAMZA ISWADI', 'SWP QGT', '2024-10-23', 'BASKARA HERUMUKTI', null, null, null],
            ['RAMZA ISWADI', 'K3U', null, null, 'LSP/BNSP', null, '2027-05-31'],
            ['RIJALUL RIZKI', 'HES Induction', '2024-04-24', 'Frans Paolo M', null, null, null],
            ['RIJALUL RIZKI', 'SWP PT HA', '2024-03-23', 'Baskara Herumukti', '100', 'PASS', null],
            ['RIJALUL RIZKI', 'K3U', null, null, 'LSP/BNSP', null, '2026-11-13'],
            ['YUDA YULIANDA PRATAMA', 'HES Induction', '2024-07-19', 'Baskara Herumukti', null, null, null],
            ['YUDA YULIANDA PRATAMA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['YUDA YULIANDA PRATAMA', 'K3U', null, null, 'LSP/BNSP', null, '2027-08-16'],
            ['SIMON PANGESTOE', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['SIMON PANGESTOE', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '87', 'PASS', null],
            ['SIMON PANGESTOE', 'K3U', null, null, 'KEMENAKER', null, '2027-08-20'],
            ['ADE PUTRA', 'HES Induction', '2023-11-22', 'SYARIFUDDIN', null, null, null],
            ['ADE PUTRA', 'SWP PT HA', '2025-01-18', 'Ade Charles', '93', 'PASS', null],
            ['ADE PUTRA', 'SWP QGT', '2025-10-15', 'HENRIYANTO', null, null, null],
            ['ADE PUTRA', 'K3U', null, null, 'KEMENAKER', null, '2026-10-29'],
            ['ANDI SAHPUTRA', 'HES Induction', '2024-07-19', 'Baskara Herumukti', null, null, null],
            ['ANDI SAHPUTRA', 'SWP PT HA', '2024-07-19', 'Baskara Herumukti', '93', 'PASS', null],
            ['ANDI SAHPUTRA', 'SWP QGT', '2025-10-15', 'HENRIYANTO', null, null, null],
            ['ANDI SAHPUTRA', 'K3U', null, null, 'LSP/BNSP', null, '2028-03-01'],
            ['SURYA DINATA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['SURYA DINATA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['SURYA DINATA', 'K3U', null, null, 'KEMENAKER', null, '2027-08-20'],
            ['EVANDRI WANDA SAPUTRA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['EVANDRI WANDA SAPUTRA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['SYAHRUL', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['SYAHRUL', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['SYAHRUL.', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['SYAHRUL.', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', null, null],
            ['SYAHRUL.', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['DODI PURNAMA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['DODI PURNAMA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '87', 'PASS', null],
            ['DODI PURNAMA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['RIO RINALDO', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['RIO RINALDO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['RIO RINALDO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['ISMET', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['ISMET', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['ISMET', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['SASNAULI LUMBAN GAOL', 'HES Induction', '2023-11-17', 'FRANS PAOLO M', null, null, null],
            ['SASNAULI LUMBAN GAOL', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', null, null],
            ['SASNAULI LUMBAN GAOL', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['UUN WAHYUDI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['UUN WAHYUDI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '80', 'PASS', null],
            ['UUN WAHYUDI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['ABDULLAH', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['ABDULLAH', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '70', 'PASS', null],
            ['ABDULLAH', 'SWP Excavation', '2025-11-19', 'ADE CHARLES', null, null, null],
            ['FENDI PULIANTO', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['FENDI PULIANTO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['HERIANCE SORMIN', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['HERIANCE SORMIN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['HERIANCE SORMIN', 'SWP Excavation', '2025-11-19', 'ADE CHARLES', null, null, null],
            ['RUSDI EFENDI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['RUSDI EFENDI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '74', 'PASS', null],
            ['RUSDI EFENDI', 'SWP Excavation', '2025-11-19', 'ADE CHARLES', null, null, null],
            ['ARIF BUDIMAN', 'HES Induction', '2023-09-18', 'BASKARA HERUMUKTI', null, null, null],
            ['ARIF BUDIMAN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['HARIS HUTABARAT', 'HES Induction', '2022-08-03', 'ENDANG Y & MARDIKAL', null, null, null],
            ['HARIS HUTABARAT', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['IRVAN', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['IRVAN', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['MASRIL', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['MASRIL', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['RUSDIYANTO', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['RUSDIYANTO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['ANDRE SYAPUTRA', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['ANDRE SYAPUTRA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '100', null, null],
            ['SUHAIMI', 'HES Induction', '2024-07-19', 'Baskara Herumukti', null, null, null],
            ['SUHAIMI', 'SWP PT HA', '2024-07-19', 'Baskara Herumukti', '93', 'PASS', null],
            ['DARMAWAN', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['DARMAWAN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['TAMBA TUA SIPAHUTAR', 'HES Induction', '2024-02-02', 'Syarifuddin', null, null, null],
            ['TAMBA TUA SIPAHUTAR', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['FADLI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['FADLI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['FADLI', 'FA DA FB', '2024-11-05', 'Hendriyanto', null, null, null],
            ['FADLI', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['FADLI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['FERI SUSANTO', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['FERI SUSANTO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['FERI SUSANTO', 'FA DA FB', '2025-05-06', 'Hendriyanto', null, null, null],
            ['FERI SUSANTO', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['SAHAT MARULI TUA SIPAHUTAR', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['SAHAT MARULI TUA SIPAHUTAR', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['SAHAT MARULI TUA SIPAHUTAR', 'FA DA FB', '2024-10-15', 'Baskara Herumukti', null, null, null],
            ['SAHAT MARULI TUA SIPAHUTAR', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['SYAFRI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['SYAFRI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['SYAFRI', 'FA DA FB', '2024-10-15', 'Baskara Herumukti', null, null, null],
            ['SYAFRI', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['SYAFRI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['FEBI PERAMA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['FEBI PERAMA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['FEBI PERAMA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['FEBI PERAMA', 'FA DA FB', '2024-11-05', 'Hendriyanto', null, null, null],
            ['FEBI PERAMA', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['PARWIRA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['PARWIRA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['PARWIRA', 'FA DA FB', '2025-01-28', 'Syarifuddin', null, null, null],
            ['PARWIRA', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['JAMI MARZUKI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['JAMI MARZUKI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['JAMI MARZUKI', 'FA DA FB', '2025-10-16', 'Novrizon Hendri', null, null, null],
            ['JAMI MARZUKI', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['JAMI MARZUKI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['RIDHO ILLAHI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['RIDHO ILLAHI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['RIDHO ILLAHI', 'FA DA FB', '2024-10-15', 'Baskara Herumukti', null, null, null],
            ['RIDHO ILLAHI', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['RIDHO ILLAHI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['MUHAMMAD IRVAN', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['MUHAMMAD IRVAN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['YUNAIDI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['YUNAIDI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['ADEK IDANA', 'HES Induction', '2023-10-16', 'BASKARA HERUMUKTI', null, null, null],
            ['ADEK IDANA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ADEK IDANA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['EZIZA PUTRA', 'HES Induction', '2023-10-16', 'BASKARA HERUMUKTI', null, null, null],
            ['EZIZA PUTRA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '87', 'PASS', null],
            ['EZIZA PUTRA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['RISMAN', 'HES Induction', '2023-06-22', 'Syarifuddin', null, null, null],
            ['RISMAN', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['RISMAN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['USMAN', 'HES Induction', '2023-05-08', 'Frans Paolo M', null, null, null],
            ['USMAN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '87', 'PASS', null],
            ['USMAN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['FAJRI KURNIAWAN', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['FAJRI KURNIAWAN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['ROZZI YANTO', 'HES Induction', '2023-11-17', 'BASKARA HERUMUKTI', null, null, null],
            ['ROZZI YANTO', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ROZZI YANTO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['M SYUKRI HANAFI', 'HES Induction', '2023-06-22', 'Syarifuddin', null, null, null],
            ['M SYUKRI HANAFI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['M SYUKRI HANAFI', 'SWP QGT', '2025-11-19', 'ADE CHARLES', null, null, null],
            ['M SYUKRI HANAFI', 'K3U', null, null, 'LSP/BNSP', null, '2027-11-07'],
            ['MARULI SITOMPUL', 'HES Induction', '2023-06-16', 'Syarifuddin', null, null, null],
            ['MARULI SITOMPUL', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['MUHAMMAD REVAL AL-AKHYAR', 'HES Induction', '2023-10-16', 'Baskara Herumukti', null, null, null],
            ['MUHAMMAD REVAL AL-AKHYAR', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['MUHAMMAD REVAL AL-AKHYAR', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['PRENGKI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['PRENGKI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['PRENGKI', 'Spotter & Flagman', '2021-11-15', null, null, null, null],
            ['PRENGKI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['WENDI RIANDA', 'HES Induction', '2023-10-16', 'BASKARA HERUMUKTI', null, null, null],
            ['WENDI RIANDA', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['WENDI RIANDA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['HENDRI NANANG', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['HENDRI NANANG', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['HENDRI NANANG', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['OVISMA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['OVISMA', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['OVISMA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['SRI YONO', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['SRI YONO', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['SRI YONO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ILHAM FAJRI WAHYUDI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['ILHAM FAJRI WAHYUDI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ILHAM FAJRI WAHYUDI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['MUHAMMAD RENO FAREZI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['MUHAMMAD RENO FAREZI', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['MUHAMMAD RENO FAREZI', 'DTAL & Spotter', '2025-05-16', 'Mardical', null, null, null],
            ['BUDI ALFAID', 'HES Induction', '2024-04-24', 'FRANS PAOLO M', null, null, null],
            ['BUDI ALFAID', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['BUDI ALFAID', 'SWP PGD', '2025-11-19', 'ADE CHARLES', null, null, null],
            ['BUDI ALFAID', 'SWP Hot Work', '2025-11-19', 'ADE CHARLES', null, null, null],
            ['M RIZKI FADLI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['M RIZKI FADLI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', null, null],
            ['DENI SUWITO', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['DENI SUWITO', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['DENI SUWITO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['PARLINDUNGAN HUTAGALUNG', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['PARLINDUNGAN HUTAGALUNG', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['PARLINDUNGAN HUTAGALUNG', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['DEDI HERMANTO', 'HES Induction', '2023-09-21', 'Baskara Herumukti', null, null, null],
            ['DEDI HERMANTO', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['DEDI HERMANTO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['TRI PRIMA DONI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['TRI PRIMA DONI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['TRI PRIMA DONI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['TRI PRIMA DONI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['DEDI SYOFIAN', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['DEDI SYOFIAN', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['DEDI SYOFIAN', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['DEDI SYOFIAN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['DONAL NAPITUPULU', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['DONAL NAPITUPULU', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '87', 'PASS', null],
            ['DONAL NAPITUPULU', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['JEKSON SINAGA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['JEKSON SINAGA', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['JEKSON SINAGA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['JEKSON SINAGA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['JHON FRENGKI SIREGAR', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['JHON FRENGKI SIREGAR', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['JHON FRENGKI SIREGAR', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['JHON FRENGKI SIREGAR', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['JONNI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['JONNI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['JONNI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['JONNI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['LEP JENDI PANE', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['LEP JENDI PANE', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['LEP JENDI PANE', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['LEP JENDI PANE', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['MARA HALIM SIREGAR', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['MARA HALIM SIREGAR', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['MARA HALIM SIREGAR', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['MARA HALIM SIREGAR', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['RONI PARTAMUAN MANALU', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['RONI PARTAMUAN MANALU', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['RONI PARTAMUAN MANALU', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ANURUL HUDA PUTRA', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['ANURUL HUDA PUTRA', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '80', 'PASS', null],
            ['ANURUL HUDA PUTRA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ANURUL HUDA PUTRA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['BUSTANUL ARIFIN', 'HES Induction', '2023-10-06', 'FAJAR RAHMAN', null, null, null],
            ['BUSTANUL ARIFIN', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['BUSTANUL ARIFIN', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['CHANDRA', 'HES Induction', '2023-10-16', 'BASKARA HERUMUKTI', null, null, null],
            ['CHANDRA', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['CHANDRA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['CHANDRA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['DASWIR', 'HES Induction', '2024-01-17', 'Rini Oktora', null, null, null],
            ['DASWIR', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['DASWIR', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['DASWIR', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['DONNI ASRI', 'HES Induction', '2024-01-17', 'Rini Oktora', null, null, null],
            ['DONNI ASRI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['DONNI ASRI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['DONNI ASRI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['MARIHOT TINAMBUNAN', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['MARIHOT TINAMBUNAN', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['MARIHOT TINAMBUNAN', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['MARIHOT TINAMBUNAN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['SEFRIANDI', 'HES Induction', '2023-02-11', 'FAJAR RAHMAN', null, null, null],
            ['SEFRIANDI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['SEFRIANDI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['SEFRIANDI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['ULYADI', 'HES Induction', '2024-01-17', 'Rini Oktora', null, null, null],
            ['ULYADI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ULYADI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ULYADI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['JONI EFFENDI', 'HES Induction', '2024-02-02', 'Syarifuddin', null, null, null],
            ['JONI EFFENDI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['JONI EFFENDI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['JONI EFFENDI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['SAIPUTRA', 'HES Induction', '2023-06-16', 'SYARIFUDDIN', null, null, null],
            ['SAIPUTRA', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['SAIPUTRA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['SAIPUTRA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['GIAN FEBRIANDES PRATAMA', 'HES Induction', '2024-07-19', 'Baskara Herumukti', null, null, null],
            ['GIAN FEBRIANDES PRATAMA', 'SWP PT HA', '2024-07-19', 'HENDRIYANTO', '93', 'PASS', null],
            ['DASRIL', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['DASRIL', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['DASRIL', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ANDRIZAL', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['ANDRIZAL', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['PARJUANGAN DANIEL IRWAN SINAGA', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['PARJUANGAN DANIEL IRWAN SINAGA', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '80', 'PASS', null],
            ['PARJUANGAN DANIEL IRWAN SINAGA', 'SWP Excavation', '2025-11-19', 'ADE CHARLES', null, null, null],
            ['VAIZ HERA', 'HES Induction', '2024-08-21', 'Syarifuddin', null, null, null],
            ['VAIZ HERA', 'SWP PT HA', '2024-08-21', 'Frans Paolo M', '93', 'PASS', null],
            ['M HUSNI IKBAL', 'HES Induction', '2023-02-16', 'Baskara Herumukti', null, null, null],
            ['M HUSNI IKBAL', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['MARDIONO', 'HES Induction', '2024-02-02', 'Syarifuddin', null, null, null],
            ['MARDIONO', 'SWP PT HA', '2024-02-02', 'FAJAR RAHMAN', '93', null, null],
            ['MARDIONO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['M EGI TIRTANA', 'HES Induction', '2024-07-19', 'Baskara Herumukti', null, null, null],
            ['M EGI TIRTANA', 'SWP PT HA', '2024-07-19', 'HENDRIYANTO', '93', 'PASS', null],
            ['M EGI TIRTANA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['JULIANTO', 'HES Induction', '2023-10-06', 'FAJAR RAHMAN', null, null, null],
            ['JULIANTO', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['MHD AZWIN', 'HES Induction', '2023-10-06', 'FAJAR RAHMAN', null, null, null],
            ['MHD AZWIN', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['MHD AZWIN', 'Training Lifting & Rigging', '2024-11-26', 'FRANS PAOLO M', null, null, null],
            ['ALFIKRI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['ALFIKRI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ALFIKRI', 'K3U', null, null, 'KEMENAKER', null, '2027-08-20'],
            ['ABDUL HARIF', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['ABDUL HARIF', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ABDUL HARIF', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['HENDRIK APIANTO', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['HENDRIK APIANTO', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ABDUL HARIS NASUTION', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['ABDUL HARIS NASUTION', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['ABDUL HARIS NASUTION', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['NELSON ROBERT SINURAT', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['NELSON ROBERT SINURAT', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['NELSON ROBERT SINURAT', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['HARIYANTO MARBUN', 'HES Induction', '2024-06-03', 'Baskara Herumukti', null, null, null],
            ['HARIYANTO MARBUN', 'SWP PT HA', '2024-06-03', 'Baskara Herumukti', '93', 'PASS', null],
            ['HARIYANTO MARBUN', 'Training Lifting & Rigging', '2024-06-06', 'FAJAR RAHMAN', null, null, null],
            ['FIRDAUS', 'HES Induction', '2023-09-21', 'Baskara Herumukti', null, null, null],
            ['FIRDAUS', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '87', 'PASS', null],
            ['SAWAL', 'HES Induction', '2023-08-24', 'Frans Paolo M', null, null, null],
            ['SAWAL', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['MUHAREL', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['MUHAREL', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '73', 'PASS', null],
            ['MUHAREL', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['DODI', 'HES Induction', '2023-09-11', 'BASKARA HERUMUKTI', null, null, null],
            ['DODI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['MARADU MANALU', 'HES Induction', '2023-09-11', 'BASKARA HERUMUKTI', null, null, null],
            ['MARADU MANALU', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['MUHARIF SAPUTRA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['MUHARIF SAPUTRA', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '80', 'PASS', null],
            ['MUHARIF SAPUTRA', 'Spotter & Flagman', '2021-10-05', null, null, null, null],
            ['RIKI RINALDI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['RIKI RINALDI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['AHMAD HAFISUDDIN NASUTION', 'HES Induction', '2024-06-03', 'Baskara Herumukti', null, null, null],
            ['AHMAD HAFISUDDIN NASUTION', 'SWP PT HA', '2024-06-03', 'HENDRIYANTO', '79', 'PASS', null],
            ['AHMAD HAFISUDDIN NASUTION', 'FA DA FB', '2024-06-04', 'Syarifuddin', null, null, null],
            ['AHMAD HAFISUDDIN NASUTION', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['RIKO MAZINER', 'HES Induction', '2023-08-28', 'Syarifuddin', null, null, null],
            ['RIKO MAZINER', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['RIKO MAZINER', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-13'],
            ['DEVI ANDRA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['DEVI ANDRA', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['DEVI ANDRA', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['DEVI ANDRA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['ROMI AGUS', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['ROMI AGUS', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '100', 'PASS', null],
            ['ROMI AGUS', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['MUHAMMAD INDRA', 'HES Induction', '2023-08-24', 'Frans Paolo M', null, null, null],
            ['MUHAMMAD INDRA', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['MUHAMMAD INDRA', 'Training Lifting & Rigging', '2024-10-17', 'BASKARA HERUMUKTI', null, null, null],
            ['SAPRIL SAMSUDIN', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['SAPRIL SAMSUDIN', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['SAPRIL SAMSUDIN', 'Spotter & Flagman', '2021-11-15', null, null, null, null],
            ['SAPRIL SAMSUDIN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['FAHMI APRIANTO', 'HES Induction', '2023-06-16', 'Syarifuddin', null, null, null],
            ['FAHMI APRIANTO', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['FAHMI APRIANTO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['YOGI SUMANTRI ARIFIN', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['YOGI SUMANTRI ARIFIN', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['YOGI SUMANTRI ARIFIN', 'Spotter & Flagman', '2021-10-05', null, null, null, null],
            ['YOGI SUMANTRI ARIFIN', 'Training Lifting & Rigging', '2024-10-17', 'BASKARA HERUMUKTI', null, null, null],
            ['ZENDRI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['ZENDRI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['MUHAMMAD YASIR SIREGAR', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['MUHAMMAD YASIR SIREGAR', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['MUHAMMAD YASIR SIREGAR', 'Spotter & Flagman', '2021-10-05', null, null, null, null],
            ['MUHAMMAD YASIR SIREGAR', 'FA DA FB', '2025-01-28', 'Syarifuddin', null, null, null],
            ['MUHAMMAD YASIR SIREGAR', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['MUHAMMAD YASIR SIREGAR', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['WILLY SEPTIAWAN', 'HES Induction', '2023-06-16', 'Syarifuddin', null, null, null],
            ['WILLY SEPTIAWAN', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['WILLY SEPTIAWAN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['NANDA AFRIYENDO', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['NANDA AFRIYENDO', 'SWP PT HA', '2024-03-01', 'Baskara Herumukti', '93', 'PASS', null],
            ['KHAIDIR', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['KHAIDIR', 'SWP PT HA', '2024-03-01', 'Baskara Herumukti', '100', 'PASS', null],
            ['KHAIDIR', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['EDI SUMADI', 'HES Induction', '2023-08-28', 'Syarifuddin', null, null, null],
            ['EDI SUMADI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '70', 'PASS', null],
            ['APRINALDO', 'HES Induction', '2023-06-22', 'Syarifuddin', null, null, null],
            ['APRINALDO', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '79', 'PASS', null],
            ['APRINALDO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['SURYA MUARIF', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['SURYA MUARIF', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['SURYA MUARIF', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['BOBI SUPARNO', 'HES Induction', '2023-08-28', 'Syarifuddin', null, null, null],
            ['BOBI SUPARNO', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['BOBI SUPARNO', 'SWP PGD', '2025-11-19', 'ADE CHARLES', null, null, null],
            ['BOBI SUPARNO', 'SWP Hot Work', '2025-11-19', 'ADE CHARLES', null, null, null],
            ['CHANDRA KIRANA', 'HES Induction', '2023-08-28', 'Syarifuddin', null, null, null],
            ['CHANDRA KIRANA', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['CHANDRA KIRANA', 'SWP PGD', '2025-09-24', 'MARDICAL', null, null, null],
            ['BAGUS BAYAZID BUSTHOMI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['BAGUS BAYAZID BUSTHOMI', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['BAGUS BAYAZID BUSTHOMI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['YUDIO ALIEF PUTRA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['YUDIO ALIEF PUTRA', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['YUDIO ALIEF PUTRA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ARI ILHAM', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['ARI ILHAM', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['ZULFIKAR', 'HES Induction', '2024-10-14', 'BASKARA HERUMUKTI', null, null, null],
            ['ZULFIKAR', 'SWP PT HA', '2024-10-14', 'Baskara Herumukti', '87', 'PASS', null],
            ['ZULFIKAR', 'FA DA FB', '2025-10-14', 'Novrizon Hendri', null, null, null],
            ['ZULFIKAR', 'SWP Otorisasi PMCOW', null, null, null, null, '2026-09-30'],
            ['RHEZA FAHLEVI', 'HES Induction', '2024-10-14', 'BASKARA HERUMUKTI', null, null, null],
            ['RHEZA FAHLEVI', 'SWP PT HA', '2024-10-14', 'Baskara Herumukti', '93', 'PASS', null],
            ['ZAINUL IKHWAN', 'HES Induction', '2024-10-14', 'BASKARA HERUMUKTI', null, null, null],
            ['ZAINUL IKHWAN', 'SWP PT HA', '2024-10-14', 'Baskara Herumukti', '86', 'PASS', null],
            ['JALPI', 'HES Induction', '2024-09-18', 'FRANS PAOLO M', null, null, null],
            ['JALPI', 'SWP PT HA', '2024-09-18', 'Baskara Herumukti', '86', 'PASS', null],
            ['JALPI', 'Training Lifting & Rigging', '2024-09-19', 'BASKARA HERUMUKTI', null, null, null],
            ['NOVRIZAL BAKHRIS', 'HES Induction', '2024-09-18', 'FRANS PAOLO M', null, null, null],
            ['NOVRIZAL BAKHRIS', 'SWP PT HA', '2024-09-18', 'Baskara Herumukti', '79', 'PASS', null],
            ['NOVRIZAL BAKHRIS', 'SWP PGD', '2025-09-24', 'MARDICAL', null, null, null],
            ['REKI WAHYUDI', 'HES Induction', '2024-10-14', 'BASKARA HERUMUKTI', null, null, null],
            ['REKI WAHYUDI', 'SWP PT HA', '2024-10-14', 'Baskara Herumukti', '86', 'PASS', null],
            ['REKI WAHYUDI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['MARWAN KONERI', 'HES Induction', '2024-11-15', 'BASKARA HERUMUKTI', null, null, null],
            ['MARWAN KONERI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['MARWAN KONERI', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['HERMANTO BUTAR-BUTAR', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['HERMANTO BUTAR-BUTAR', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['HERMANTO BUTAR-BUTAR', 'SWP PGD', '2025-09-24', 'MARDICAL', null, null, null],
            ['HERU SEPRIWAN', 'HES Induction', '2024-10-28', 'BASKARA HERUMUKTI', null, null, null],
            ['HERU SEPRIWAN', 'SWP PT HA', '2024-10-14', 'Baskara Herumukti', '93', 'PASS', null],
            ['HERU SEPRIWAN', 'SWP QGT', '2025-11-19', 'ADE CHARLES', null, null, null],
            ['HERU SEPRIWAN', 'K3U', null, null, 'LSP/BNSP', null, '2025-11-15'],
            ['DIMAS AD', 'HES Induction', '2023-12-13', 'Rini Oktora', null, null, null],
            ['DIMAS AD', 'SWP PT HA', '2024-10-13', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['MUJIONO', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['MUJIONO', 'SWP PT HA', '2024-09-17', 'IRFAN DASMANTO', '86', 'PASS', null],
            ['MUJIONO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['MUJIONO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['HASBI SETIAWAN', 'HES Induction', '2024-07-10', 'FAJAR RAHMAN', null, null, null],
            ['HASBI SETIAWAN', 'SWP PT HA', '2024-09-21', 'IRFAN DASMANTO', '93', 'PASS', null],
            ['HASBI SETIAWAN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['SASTRO FERNANDO', 'HES Induction', '2024-10-24', 'BASKARA HERUMUKTI', null, null, null],
            ['SASTRO FERNANDO', 'SWP PT HA', '2024-10-24', 'Baskara Herumukti', '93', 'PASS', null],
            ['SASTRO FERNANDO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['MUHAMMAD FIRDAUS', 'HES Induction', '2024-11-15', 'BASKARA HERUMUKTI', null, null, null],
            ['MUHAMMAD FIRDAUS', 'SWP PT HA', '2024-11-15', 'Baskara Herumukti', null, 'PASS', null],
            ['MUHAMMAD FIRDAUS', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['MUHAMMAD FIRDAUS', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['NOVAL BATUBARA', 'HES Induction', '2024-10-28', 'Syarifuddin', null, null, null],
            ['NOVAL BATUBARA', 'SWP PT HA', '2024-10-25', 'Mardikal', '93', 'PASS', null],
            ['NOVAL BATUBARA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['MUHAMMAD HASEB', 'HES Induction', '2024-11-15', 'BASKARA HERUMUKTI', null, null, null],
            ['MUHAMMAD HASEB', 'SWP PT HA', '2024-11-28', 'Ade Charles', '93', 'PASS', null],
            ['IBNU FAJAR FATIHAN', 'HES Induction', '2024-11-15', 'BASKARA HERUMUKTI', null, null, null],
            ['IBNU FAJAR FATIHAN', 'SWP PT HA', '2024-11-15', 'Baskara Herumukti', '93', 'PASS', null],
            ['IBNU FAJAR FATIHAN', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['MUHAMMAD SYAIFULLAH', 'HES Induction', '2024-11-28', 'BASKARA HERUMUKTI', null, null, null],
            ['MUHAMMAD SYAIFULLAH', 'SWP PT HA', '2024-11-28', 'Ade Charles', null, 'PASS', null],
            ['MUHAMMAD SYAIFULLAH', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['ADE TRINANDA', 'HES Induction', '2024-05-15', 'Rini Oktora', null, null, null],
            ['ADE TRINANDA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ADE TRINANDA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['BENI PUTRA', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['BENI PUTRA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['BENI PUTRA', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['DIMAS SEPTIANDO', 'HES Induction', '2023-12-13', 'Rini Oktora', null, null, null],
            ['DIMAS SEPTIANDO', 'SWP PT HA', null, 'Baskara Herumukti', '93', 'PASS', null],
            ['DIMAS SEPTIANDO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['DIMAS SEPTIANDO', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['NAZARUDDIN', 'HES Induction', '2023-10-06', 'FAJAR RAHMAN', null, null, null],
            ['NAZARUDDIN', 'SWP PT HA', null, 'Mardikal', '80', 'PASS', null],
            ['NAZARUDDIN', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['NAZARUDDIN', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['Ali Zar', 'HES Induction', '2023-03-02', 'Baskara Herumukti', null, null, null],
            ['Ali Zar', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['Ali Zar', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['Eri Yusman', 'HES Induction', '2023-03-02', 'Baskara Herumukti', null, null, null],
            ['Eri Yusman', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['Eri Yusman', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['Bobby', 'HES Induction', '2025-01-10', 'Baskara Herumukti', null, null, null],
            ['Bobby', 'SWP PT HA', null, 'Baskara Herumukti', '93', 'PASS', null],
            ['Bobby', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['Bobby', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['Wahyu Rio Prima', 'HES Induction', '2024-08-21', 'Syarifuddin', null, null, null],
            ['Wahyu Rio Prima', 'SWP PT HA', '2024-08-21', 'Frans Paolo M', '100', 'PASS', null],
            ['Wahyu Rio Prima', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['Pascal Wilmar Dinov', 'HES Induction', '2025-05-19', 'Rini Oktora', null, null, null],
            ['Pascal Wilmar Dinov', 'SWP PT HA', null, 'RINI OKTORA', '81', 'PASS', null],
            ['Husein Al Hafiz', 'HES Induction', '2025-06-30', 'FRANS PAOLO M', null, null, null],
            ['Husein Al Hafiz', 'SWP PT HA', null, 'Frans Paolo M', '93', 'PASS', null],
            ['Husein Al Hafiz', 'DTAL & Spotter', '2025-06-22', 'Fajar Rahman', null, null, null],
            ['Syahrullah', 'HES Induction', '2024-11-15', 'Baskara Herumukti', null, null, null],
            ['Syahrullah', 'SWP PT HA', null, 'Baskara Herumukti', '93', 'PASS', null],
            ['Syahrullah', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['Erianda Perdana', 'HES Induction', '2025-07-18', 'MARDIKAL', null, null, null],
            ['Erianda Perdana', 'SWP PT HA', null, 'Frans Paolo M', '93', 'PASS', null],
            ['Aththaariq Muhammad Y', 'HES Induction', '2025-07-18', 'MARDIKAL', null, null, null],
            ['Aththaariq Muhammad Y', 'SWP PT HA', null, 'Frans Paolo M', '87', 'PASS', null],
            ['Supriadi', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['Supriadi', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['Supriadi', 'DTAL & Spotter', '2025-05-03', 'Ade charles', null, null, null],
            ['AMAN JEFRI NAINGGOLAN', 'HES Induction', '2025-06-13', 'FAJAR RAHMAN', null, null, null],
            ['AMAN JEFRI NAINGGOLAN', 'SWP PT HA', '2025-06-13', 'FAJAR RAHMAN', '86', 'PASS', null],
            ['AMAN JEFRI NAINGGOLAN', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['YUSWARDI', 'HES Induction', '2025-05-26', 'FAJAR RAHMAN', null, null, null],
            ['YUSWARDI', 'SWP PT HA', null, 'FAJAR RAHMAN', null, 'PASS', null],
            ['JONI MUSKARIANTO', 'HES Induction', '2025-04-09', 'MARDIKAL', null, null, null],
            ['JONI MUSKARIANTO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ABDURRAHMAN IBRAHIM', 'HES Induction', '2026-05-15', 'FAJAR RAHMAN', null, null, null],
            ['ABDURRAHMAN IBRAHIM', 'SWP PT HA', null, 'HENRIYANTO', '93', 'PASS', null],
            ['ABDURRAHMAN IBRAHIM', 'Training Lifting & Rigging', '2025-05-20', 'ADE CHARLES', null, null, null],
            ['DEDE MARTIN', 'HES Induction', '2026-01-29', 'ADE CHARLES', null, null, null],
            ['AHMAD BARON MARCELLO', 'HES Induction', '2025-05-26', 'FAJAR RAHMAN', null, null, null],
            ['AHMAD BARON MARCELLO', 'SWP PT HA', '2025-05-26', 'FAJAR RAHMAN', '86', 'PASS', null],
            ['AHMAD BARON MARCELLO', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['RIRI PUTRA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['RIRI PUTRA', 'SWP PT HA', '2025-06-13', 'FAJAR RAHMAN', '86', 'PASS', null],
            ['RIRI PUTRA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['HAMDANI', 'HES Induction', '2023-05-08', 'FRANS PAOLO M', null, null, null],
            ['HAMDANI', 'SWP PT HA', '2025-06-13', 'FAJAR RAHMAN', '79', 'PASS', null],
            ['HAMDANI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['AGRIANDI', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['AGRIANDI', 'SWP PT HA', '2024-07-04', 'FAJAR RAHMAN', '93', 'PASS', null],
            ['AGRIANDI', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['ANDRI SAPUTRA', 'HES Induction', '2023-03-10', 'BASKARA HERUMUKTI', null, null, null],
            ['ANDRI SAPUTRA', 'SWP PT HA', '2025-06-13', 'FAJAR RAHMAN', '79', 'PASS', null],
            ['ANDRI SAPUTRA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['PUTRA MULIA', 'HES Induction', '2025-07-01', 'FRANS PAOLO M', null, null, null],
            ['PUTRA MULIA', 'SWP PT HA', '2025-06-30', 'Frans Paolo M', '86', 'PASS', null],
            ['PUTRA MULIA', 'MVSHE & LV', null, null, null, 'PASS', null],
            ['M NASIR SYAHPUTRA', 'HES Induction', '2023-06-23', 'HENDRIYANTO', null, null, null],        ];

        $updated = 0; $skipped = 0; $notFound = 0;
        foreach ($data as [$empName, $jenisTraining, $tanggal, $trainer, $nilai, $status, $expired]) {
            // Find employee
            $emp = Employee::whereRaw('UPPER(TRIM(nama_lengkap)) = ?', [strtoupper(trim($empName))])->first();
            if (!$emp) {
                $parts = explode(' ', strtoupper(trim($empName)));
                if (count($parts) >= 2) {
                    $emp = Employee::whereRaw('UPPER(nama_lengkap) LIKE ?', [$parts[0].'%'.$parts[1].'%'])->first();
                }
            }
            if (!$emp) { $notFound++; continue; }

            $typeId = $typeMap[$jenisTraining] ?? null;
            if (!$typeId) { $skipped++; continue; }

            EmployeeTraining::updateOrCreate(
                ['employee_id' => $emp->id, 'training_type_id' => $typeId],
                array_filter([
                    'tanggal'      => $tanggal,
                    'nama_trainer' => $trainer,
                    'nilai'        => $nilai,
                    'status'       => $status,
                    'expired_date' => $expired,
                ], fn($v) => $v !== null)
            );
            $updated++;
        }

        $this->command->info("✅ Training records: {$updated} berhasil");
        if ($skipped)   $this->command->warn("⚠️  Skipped: {$skipped}");
        if ($notFound)  $this->command->warn("⚠️  Karyawan tidak ditemukan: {$notFound}");
    }
}
