<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;

class UpdateMcuSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['BAWONO WIJAYANTO WIRANJAYA', '2026-09-24', 'OK', 'RS MUTIA SARI'],
            ['SUNARTO', '2026-05-09', 'OK', 'RS MUTIA SARI'],
            ['YASNI PINAL', '2026-09-27', 'OK', 'RS MUTIA SARI'],
            ['SATRIA AFRIZA', '2026-07-02', 'OK', 'RS MUTIA SARI'],
            ['JOSUA WIRONI HUTASOIT', '2026-07-05', 'OK', 'RS MUTIA SARI'],
            ['FAJAR FEBRIAN', '2026-10-04', 'OK', 'RS MUTIA SARI'],
            ['M PRIYO SUDARMONO', '2026-09-26', 'OK', 'RS MUTIA SARI'],
            ['IRFAN DASMANTO', '2026-09-24', 'OK', 'RS MUTIA SARI'],
            ['M ALIEF DARMAWANSYAH', '2027-01-23', 'OK', 'RS MUTIA SARI'],
            ['TRIO WASIAM', null, 'OK', 'RS MUTIA SARI'],
            ['MARTIN FERNANDO SIREGAR', null, 'OK', 'RS MUTIA SARI'],
            ['ADIN RIZKY KUMARA', null, 'OK', 'RS MUTIA SARI'],
            ['MUHAMMAD RAPIQI', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['HAVIZ AL RASYID', '2026-09-21', 'OK', 'LABORATORIUM KLINIK THAMRIN'],
            ['OKI CHARLES', '2026-10-07', 'OK', 'RS MUTIA SARI'],
            ['JHON HENDRI', '2026-07-20', 'OK', 'RS MUTIA SARI'],
            ['SUPRIADI', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['AHMAD SYAH', '2026-06-22', 'OK', 'RS MUTIA SARI'],
            ['AZLAN EFENDI', '2026-06-22', 'OK', 'RS MUTIA SARI'],
            ['BUDI HANDOKO', '2026-04-12', 'OK', 'RS MUTIA SARI'],
            ['DEDEK SUSANTO', '2026-12-26', 'OK', 'RS MUTIA SARI'],
            ['DISYA  AIDIL KOSI', null, 'OK', 'RS MUTIA SARI'],
            ['IDRIS', '2026-08-10', 'OK', 'RS MUTIA SARI'],
            ['LACTOGEN NAINGGOLAN', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['M NUR', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['RATNO WIYONO', '2026-09-21', 'OK', 'LABORATORIUM KLINIK THAMRIN'],
            ['SATRIYON', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['ALMEDI INDRA', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['ANDRE ISMAWIR', '2026-03-17', 'OK', 'RS MUTIA SARI'],
            ['BAHTERA NEDI', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['ANDRI', '2026-08-10', 'OK', 'RS MUTIA SARI'],
            ['ANRIZAL', null, 'OK', 'RS MUTIA SARI'],
            ['BUJANG PAMAN', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['DENI ADE PUTRA', '2026-08-07', 'OK', 'RS MUTIA SARI'],
            ['JUFRIZAL', '2026-04-02', 'OK', 'RS MUTIA SARI'],
            ['KISWADI', '2026-08-08', 'OK', 'RS MUTIA SARI'],
            ['MASRIL WISWA', null, 'OK', 'RS MUTIA SARI'],
            ['MUHAMMADDIN', null, 'OK', 'RS MUTIA SARI'],
            ['NAHARUDIN', '2026-11-30', 'OK', 'LABORATORIUM KLINIK THAMRIN'],
            ['NURDIANTO', '2026-04-03', 'OK', 'LABORATORIUM KLINIK THAMRIN'],
            ['RABIYATUL MIRANDA', null, 'OK', 'RS MUTIA SARI'],
            ['SYAFRI ADI', '2026-06-22', 'OK', 'RS MUTIA SARI'],
            ['SYAFRIZON', null, 'OK', 'RS MUTIA SARI'],
            ['TARULI NAIBAHO', '2026-06-22', 'OK', 'RS MUTIA SARI'],
            ['TUKINO', '2026-08-10', 'OK', 'RS MUTIA SARI'],
            ['YULHENDRI', '2026-06-22', 'OK', 'RS MUTIA SARI'],
            ['YUNASRIL', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['DEZITA CHANDRA', '2026-10-06', 'OK', 'RS MUTIA SARI'],
            ['MUSTAFA', null, 'OK', 'RS MUTIA SARI'],
            ['HENDRA FERI', '2026-08-14', 'OK', 'RS MUTIA SARI'],
            ['ROBBI SAPUTRA', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['WELDI RUSDI', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['DAMAR WULAN', '2026-08-23', 'OK', 'RS MUTIA SARI'],
            ['ABDUL RAHMAN', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['IRVAN LUTFI', '2026-07-06', 'OK', 'RS MUTIA SARI'],
            ['UMAR ARIS MUNADAR', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['BAMBANG TRISNO', '2026-10-02', 'OK', 'RS MUTIA SARI'],
            ['SALMAN SYOBRI', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['WAWAN RIANDRA', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['R GARRY PATRIA', '2026-06-21', 'OK', 'RS MUTIA SARI'],
            ['ERI SUDHARMAN', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['WIHANDRI SENJAYA', '2026-08-09', 'OK', 'RS MUTIA SARI'],
            ['ALENDRA NAULY.S', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['RAFICO ADE MARTA', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['MUHAMMAD AGUNG PERDANA', '2026-08-07', 'OK', 'RS MUTIA SARI'],
            ['RAMZA ISWADI', '2026-04-12', 'OK', 'RS MUTIA SARI'],
            ['RIJALUL RIZKI', '2026-04-14', 'OK', 'RS MUTIA SARI'],
            ['YUDA YULIANDA PRATAMA', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['SIMON PANGESTOE', '2026-08-14', 'OK', 'RS MUTIA SARI'],
            ['ADE PUTRA', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['ANDI SAHPUTRA', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['SURYA DINATA', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['EVANDRI WANDA SAPUTRA', '2026-08-25', 'OK', 'RS MUTIA SARI'],
            ['SYAHRUL', '2026-09-01', 'OK', 'RS MUTIA SARI'],
            ['DODI PURNAMA', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['RIO RINALDO', '2026-08-09', 'OK', 'RS MUTIA SARI'],
            ['SYAHRUL.', null, 'OK', 'RS MUTIA SARI'],
            ['ISMET', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['SASNAULI LUMBAN GAOL', '2026-09-15', 'OK', 'RS MUTIA SARI'],
            ['UUN WAHYUDI', '2026-07-31', 'OK', 'RS MUTIA SARI'],
            ['ABDULLAH', '2026-07-20', 'OK', 'RS MUTIA SARI'],
            ['DENY WIDYANSAH', null, 'OK', 'RS MUTIA SARI'],
            ['FENDI PULIANTO', '2026-11-30', 'OK', 'RS MUTIA SARI'],
            ['HERIANCE SORMIN', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['RUSDI EFENDI', '2026-04-26', 'OK', 'RS MUTIA SARI'],
            ['ARIF BUDIMAN', '2026-10-17', 'OK', 'RS MUTIA SARI'],
            ['HARIS HUTABARAT', '2026-10-18', 'OK', 'RS MUTIA SARI'],
            ['IRVAN', '2026-09-08', 'OK', 'RS MUTIA SARI'],
            ['MASRIL', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['RUSDIYANTO', '2026-10-03', 'OK', 'RS MUTIA SARI'],
            ['ANDRE SYAPUTRA', '2026-09-22', 'OK', 'RS MUTIA SARI'],
            ['SUHAIMI', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['DARMAWAN', '2026-09-22', 'OK', 'RS MUTIA SARI'],
            ['TAMBA TUA SIPAHUTAR', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['ALVARIZA DANDY PERDANA', null, 'OK', 'RS MUTIA SARI'],
            ['FADLI', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['FERI SUSANTO', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['SAHAT MARULI TUA SIPAHUTAR', '2026-10-18', 'OK', 'RS MUTIA SARI'],
            ['SYAFRI', '2026-08-23', 'OK', 'RS MUTIA SARI'],
            ['FEBI PERAMA', '2026-06-21', 'OK', 'RS MUTIA SARI'],
            ['PARWIRA', '2026-06-21', 'OK', 'RS MUTIA SARI'],
            ['JAMI MARZUKI', '2026-08-10', 'OK', 'RS MUTIA SARI'],
            ['RIDHO ILLAHI', '2026-08-09', 'OK', 'RS MUTIA SARI'],
            ['MUHAMMAD IRVAN', '2026-08-25', 'OK', 'RS MUTIA SARI'],
            ['M RAFI PRATAMA YOSEFANNY', null, 'OK', 'RS MUTIA SARI'],
            ['YUNAIDI', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['RHOBERT', null, 'OK', 'RS MUTIA SARI'],
            ['ROMI FERIZAL', null, 'OK', 'RS MUTIA SARI'],
            ['ADEK IDANA', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['EZIZA PUTRA', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['RISMAN', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['USMAN', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['FAJRI KURNIAWAN', '2026-03-20', 'OK', 'RS MUTIA SARI'],
            ['ROZZI YANTO', '2026-08-23', 'OK', 'RS MUTIA SARI'],
            ['M SYUKRI HANAFI', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['MARULI SITOMPUL', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['MUHAMMAD REVAL AL-AKHYAR', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['PRENGKI', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['WENDI RIANDA', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['NEDRIYANTO', null, 'OK', 'RS MUTIA SARI'],
            ['HENDRI NANANG', '2026-10-30', 'OK', 'RS MUTIA SARI'],
            ['OVISMA', '2026-09-24', 'OK', 'RS MUTIA SARI'],
            ['SRI YONO', '2026-09-24', 'OK', 'RS MUTIA SARI'],
            ['FATUR RAHMAN HAKAM', null, 'OK', 'RS MUTIA SARI'],
            ['HABIBUR RAMADHAN', '2026-08-07', 'OK', 'RS MUTIA SARI'],
            ['ILHAM FAJRI WAHYUDI', '2026-07-20', 'OK', 'RS MUTIA SARI'],
            ['MUHAMMAD RENO FAREZI', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['BUDI ALFAID', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['M RIZKI FADLI', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['DENI SUWITO', '2026-09-15', 'OK', 'RS MUTIA SARI'],
            ['SUPARMAN', '2026-09-03', 'OK', 'RS MUTIA SARI'],
            ['PARLINDUNGAN HUTAGALUNG', '2026-08-10', 'OK', 'RS MUTIA SARI'],
            ['DEDI HERMANTO', '2026-08-07', 'OK', 'RS MUTIA SARI'],
            ['TRI PRIMA DONI', '2026-08-10', 'OK', 'RS MUTIA SARI'],
            ['ALI USMAN', null, 'OK', 'RS MUTIA SARI'],
            ['DEDI SYOFIAN', '2026-06-22', 'OK', 'RS MUTIA SARI'],
            ['DONAL NAPITUPULU', '2026-08-09', 'OK', 'RS MUTIA SARI'],
            ['JEKSON SINAGA', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['JHON FRENGKI SIREGAR', '2026-08-07', 'OK', 'RS MUTIA SARI'],
            ['JONNI', '2026-07-27', 'OK', 'RS MUTIA SARI'],
            ['LEP JENDI PANE', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['MARA HALIM SIREGAR', '2026-08-10', 'OK', 'RS MUTIA SARI'],
            ['RONI PARTAMUAN MANALU', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['AAN HERYANTO', null, 'OK', 'RS MUTIA SARI'],
            ['ANURUL HUDA PUTRA', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['BUSTANUL ARIFIN', '2026-04-12', 'OK', 'RS MUTIA SARI'],
            ['CHANDRA', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['DASWIR', '2026-11-30', 'OK', 'RS MUTIA SARI'],
            ['DENY', null, 'OK', 'RS MUTIA SARI'],
            ['DONNI ASRI', '2026-11-30', 'OK', 'RS MUTIA SARI'],
            ['EDI CHANDRA', null, 'OK', 'RS MUTIA SARI'],
            ['HENDRA MULYADI', '2026-10-07', 'OK', 'RS MUTIA SARI'],
            ['HENDRI YADI', null, 'OK', 'RS MUTIA SARI'],
            ['MARIHOT TINAMBUNAN', '2026-08-06', 'OK', 'RS MUTIA SARI'],
            ['SEFRIANDI', '2026-07-20', 'OK', 'RS MUTIA SARI'],
            ['SUYATNO', null, 'OK', 'RS MUTIA SARI'],
            ['ULYADI', '2026-11-30', 'OK', 'RS MUTIA SARI'],
            ['JONI EFFENDI', '2026-04-12', 'OK', 'RS MUTIA SARI'],
            ['SAIPUTRA', '2026-10-06', 'OK', 'RS MUTIA SARI'],
            ['GIAN FEBRIANDES PRATAMA', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['DASRIL', '2026-12-26', 'OK', 'RS MUTIA SARI'],
            ['ANDRIZAL', '2026-08-08', 'OK', 'RS MUTIA SARI'],
            ['PARJUANGAN DANIEL IRWAN SINAGA', '2026-08-13', 'OK', 'RS MUTIA SARI'],
            ['VAIZ HERA', '2026-08-13', 'OK', 'RS MUTIA SARI'],
            ['JHONNY YUNASRI', null, 'OK', 'RS MUTIA SARI'],
            ['M HUSNI IKBAL', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['DANIL GUSTIAR', null, 'OK', 'RS MUTIA SARI'],
            ['MARDIONO', '2026-04-14', 'OK', 'RS MUTIA SARI'],
            ['M EGI TIRTANA', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['JULIANTO', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['MHD AZWIN', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['NUR IRWANTO', '2026-04-12', 'OK', 'RS MUTIA SARI'],
            ['ALFIKRI', '2026-08-08', 'OK', 'RS MUTIA SARI'],
            ['ABDUL HARIF', '2026-08-23', 'OK', 'RS MUTIA SARI'],
            ['HENDRIK APIANTO', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['ABDUL HARIS NASUTION', '2026-03-24', 'OK', 'RS MUTIA SARI'],
            ['NELSON ROBERT SINURAT', '2026-04-22', 'OK', 'RS MUTIA SARI'],
            ['JUMADI', null, 'OK', 'RS MUTIA SARI'],
            ['HARIYANTO MARBUN', '2026-05-18', 'OK', 'RS MUTIA SARI'],
            ['FIRDAUS', '2026-08-09', 'OK', 'RS MUTIA SARI'],
            ['SAWAL', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['MUHAREL', '2026-08-09', 'OK', 'RS MUTIA SARI'],
            ['DODI', '2026-08-10', 'OK', 'RS MUTIA SARI'],
            ['MARADU MANALU', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['MUHARIF SAPUTRA', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['RIKI RINALDI', '2026-09-24', 'OK', 'RS MUTIA SARI'],
            ['AHMAD HAFISUDDIN NASUTION', '2026-05-18', 'OK', 'RS MUTIA SARI'],
            ['RIKO MAZINER', '2026-08-10', 'OK', 'RS MUTIA SARI'],
            ['DEVI ANDRA', '2026-08-08', 'OK', 'RS MUTIA SARI'],
            ['ROMI AGUS', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['MUHAMMAD INDRA', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['SAPRIL SAMSUDIN', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['FAHMI APRIANTO', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['YOGI SUMANTRI ARIFIN', '2026-08-10', 'OK', 'RS MUTIA SARI'],
            ['ZENDRI', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['MUHAMMAD YASIR SIREGAR', '2026-08-10', 'OK', 'RS MUTIA SARI'],
            ['WILLY SEPTIAWAN', '2026-08-08', 'OK', 'RS MUTIA SARI'],
            ['NANDA AFRIYENDO', '2026-03-17', 'OK', 'RS MUTIA SARI'],
            ['KHAIDIR', '2026-11-30', 'OK', 'RS MUTIA SARI'],
            ['EDI SUMADI', '2026-11-30', 'OK', 'RS MUTIA SARI'],
            ['APRINALDO', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['SURYA MUARIF', '2026-06-15', 'OK', 'RS MUTIA SARI'],
            ['BOBI SUPARNO', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['CHANDRA KIRANA', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['BAGUS BAYAZID BUSTHOMI', '2026-10-06', 'OK', 'RS MUTIA SARI'],
            ['YUDIO ALIEF PUTRA', null, 'OK', 'RS MUTIA SARI'],
            ['ARI ILHAM', '2026-12-08', 'OK', 'RS MUTIA SARI'],
            ['ZULFIKAR', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['RHEZA FAHLEVI', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['ZAINUL IKHWAN', '2026-10-06', 'OK', 'RS MUTIA SARI'],
            ['JALPI', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['NOVRIZAL BAKHRIS', '2026-08-24', 'OK', 'RS MUTIA SARI'],
            ['DAMRI GAJAH', null, 'OK', 'RS MUTIA SARI'],
            ['JUNAIDI', null, 'OK', 'RS MUTIA SARI'],
            ['REKI WAHYUDI', '2026-09-21', 'OK', 'RS MUTIA SARI'],
            ['SYAHRIAL', null, 'OK', 'RS MUTIA SARI'],
            ['HENDRA SUYATA', null, 'OK', 'RS MUTIA SARI'],
            ['ALMENDO RAFKI', null, 'OK', 'RS MUTIA SARI'],
            ['MARWAN KONERI', '2026-03-24', 'OK', 'RS MUTIA SARI'],
            ['SAFEN MULIA RAMADHAN', null, 'OK', 'RS MUTIA SARI'],
            ['NICO PRASETYO', null, 'OK', 'RS MUTIA SARI'],
            ['ABDULLAH ALFARUQI', null, 'OK', 'RS MUTIA SARI'],
            ['TEGUH ZIKRI KURNIAWAN', null, 'OK', 'RS MUTIA SARI'],
            ['MUHAMMAD RIDHO', null, 'OK', 'RS MUTIA SARI'],
            ['FIKRI RIZALDI', null, 'OK', 'RS MUTIA SARI'],
            ['ERICK', null, 'OK', 'RS MUTIA SARI'],
            ['HERMANTO BUTAR-BUTAR', null, 'OK', 'RS MUTIA SARI'],
            ['HERU SEPRIAWAN', null, 'OK', 'RS MUTIA SARI'],
            ['DIMAS AD', '2026-10-18', 'OK', 'RS MUTIA SARI'],
            ['MUJIONO', '2026-06-22', 'OK', 'RS MUTIA SARI'],
            ['HASBI SETIAWAN', '2026-06-15', 'OK', 'RS MUTIA SARI']
        ];

        $updated = 0;
        foreach ($data as $d) {
            $emp = Employee::whereRaw('UPPER(nama_lengkap) = ?', [strtoupper($d[0])])->first();
            if ($emp) {
                $emp->update([
                    'exp_mcu'    => $d[1],
                    'status_mcu' => $d[2],
                    'lokasi_mcu' => $d[3],
                ]);
                $updated++;
            }
        }
        $this->command->info("✅ MCU updated: {$updated} karyawan");
    }
}
